CREATE TABLE IF NOT EXISTS comments (
    id SERIAL PRIMARY KEY,
    topic_id INTEGER NOT NULL,
    author VARCHAR(100) NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);